import type { NextConfig } from "next";
import redirects from "./content/redirects.json";

const nextConfig: NextConfig = {
  trailingSlash: true, // WordPress URLs end in "/"
  async redirects() {
    return redirects; // generated by scripts/import-wp.mjs
  },
};

export default nextConfig;
