import { readdirSync, readFileSync } from "node:fs";
import type { Metadata } from "next";

// Generated by scripts/import-wp.mjs. Do not edit content/pages/*.json by hand.
export type Family = "home" | "service" | "cityHub" | "cityService" | "article" | "generic";

export type Page = {
  path: string; // "/digital-marketing-services/seo-services/"
  type: "page" | "post";
  wpId: number;
  family: Family;
  wpTemplate: string;
  title: string;
  date: string;
  modified: string;
  seo: { title: string; canonical?: string; meta: [string, string][] };
  jsonLd: object[];
  html: string;
};

const DIR = "content/pages";

let cache: Page[] | undefined;
export function getAllPages(): Page[] {
  cache ??= readdirSync(DIR)
    .filter((f) => f.endsWith(".json"))
    .map((f) => JSON.parse(readFileSync(`${DIR}/${f}`, "utf8")));
  return cache;
}

export function getPage(slug: string[] = []): Page | undefined {
  const path = slug.length ? `/${slug.map(decodeURIComponent).join("/")}/` : "/";
  return getAllPages().find((p) => p.path === path);
}

// Rank Math <head> tags -> Next Metadata. Anything Next has no field for goes to `other`.
export function toMetadata({ seo }: Page): Metadata {
  const m = new Map<string, string>();
  const other: Record<string, string> = {};
  for (const [k, v] of seo.meta) m.set(k, v);
  const take = (k: string) => {
    const v = m.get(k);
    m.delete(k);
    return v;
  };
  const num = (v?: string) => (v ? Number(v) : undefined);

  const image = take("og:image");
  const ogType = take("og:type");
  const isArticle = ogType === "article"; // Next only emits article:* for og:type article
  const metadata: Metadata = {
    title: { absolute: seo.title },
    description: take("description"),
    robots: take("robots"),
    alternates: seo.canonical ? { canonical: seo.canonical } : undefined,
    openGraph: {
      locale: take("og:locale"),
      type: ogType as "website" | "article",
      title: take("og:title"),
      description: take("og:description"),
      url: take("og:url"),
      siteName: take("og:site_name"),
      images: image && {
        url: image,
        secureUrl: take("og:image:secure_url"),
        width: num(take("og:image:width")),
        height: num(take("og:image:height")),
        alt: take("og:image:alt"),
        type: take("og:image:type"),
      },
      videos: m.has("og:video") ? [{ url: take("og:video")! }] : undefined,
      ...(isArticle && {
        publishedTime: take("article:published_time"),
        modifiedTime: take("article:modified_time"),
        section: take("article:section"),
      }),
    } as Metadata["openGraph"],
    twitter: {
      card: take("twitter:card") as "summary_large_image",
      title: take("twitter:title"),
      description: take("twitter:description"),
      images: take("twitter:image"),
    },
  };
  for (const [k, v] of m) other[k] = v; // twitter:label1/data1, og:updated_time, ...
  metadata.other = other;
  return metadata;
}
